### ISSUE TITLE
Gear log: issues reading from uploaded XLSX file

### ISSUE THREAD

**Issue by lhmarsden** [SIOS-Svalbard/darwinsheet#6]
I have been working on a tool that will automatically generate an XLSX of the gear log from data on IMR's onboard API. This tool will:
1. Generate a new XLSX file if the user doesn't already have one.
2.  If the user already has a file, they can upload that file. This tool will copy the contents of this file into a pandas dataframe and append only new 'activities' (with new eventIDs) to it. A new file will then be generated. This therefore preserves and changes that the user has made to data for past activities.

This works fine for 1. However, for 2, I am having problems. To read from an uploaded file, I must first save it locally. However, this step is not working. I have isolated this issue to lines 74 to 77 in gear_xlsx.cgi.

@paalge any idea what I am missing?

According to this, this should be working... Perhaps something to do with working with a virtual machine?
https://stackoverflow.com/questions/65249837/read-from-uploaded-xlsx-file-in-python-cgi-script-using-pandas

Luke.

**Comment by lhmarsden** [comment]
Quick update. I have enabled the 'cgitb' module import cgitb, cgitb.enable at the beginning of the script. Now, the XLSX file output has a file size of 23 KB. When I open this in a text editor I can see an error log that includes a description of the error from Python - as you would see if you were running a .py file.

This is something that I should be able to fix, and will close this issue when it is done.

**Comment by paalge** [comment]
I would assume it has something to do with file permissions. Though you should be able to only hold it in memory with a virtual file in python https://stackoverflow.com/questions/18550127/how-to-do-virtual-file-processing

**Comment by lhmarsden** [comment]
Thanks @paalge for taking a look. I have fixed this now. It turns out that the issue was actually that when I was reading in the data from the old excel sheet, blank cells were stored as NANs in the dataframe. These could not be directly written out to another Excel file, so I have made these cells empty again. This issue will now be closed.
